version: '3'
services:
  fusio-plant:
    build: fusio/plant
    restart: always
    environment:
      FUSIO_TENANT_ID: ""
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_URL: "http://api.fusio.cloud:8080"
      FUSIO_APPS_URL: "http://api.fusio.cloud:8080/apps"
      FUSIO_ENV: "prod"
      FUSIO_DEBUG: "false"
      FUSIO_CONNECTION: "pdo-mysql://fusio:61ad6c605975@mysql-fusio/fusio"
      FUSIO_BACKEND_USER: "test"
      FUSIO_BACKEND_EMAIL: "demo@fusio-project.org"
      FUSIO_BACKEND_PW: "test1234"
      FUSIO_MAILER: "native://default"
      FUSIO_MESSENGER: "doctrine://default"
      FUSIO_MAIL_SENDER: "info@api.fusio.cloud"
      FUSIO_TRUSTED_IP_HEADER: ""
    links:
      - mysql-fusio
    ports:
      - "8080:80"

  mysql-fusio:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_USER: "fusio"
      MYSQL_PASSWORD: "61ad6c605975"
      MYSQL_DATABASE: "fusio"
    volumes:
      - ./db:/var/lib/mysql
